// Grammar for versions:    2.0    2.2                         2.6    2.7
// Generated by CompareGrammar on 2018-01-16 at 20:28:53.034+00:00


%%

%public
funcdef:
	  DEF NAME parameters COLON suite
	{} ;


%%


