// Grammar for versions:           2.2    2.4  2.4.3                     
// Generated by CompareGrammar on 2018-01-16 at 20:28:52.952+00:00


// Top non-terminals: testlist_safe yield_stmt


%%

%public
testlist_safe:
	  test _optional(_plus(COMMA test {}) _optional(COMMA {}) {})
	{} ;

%public
yield_stmt:
	  YIELD testlist
	{} ;


%%


