// Grammar for versions:    3.0                                   
// Generated by CompareGrammar on 2018-01-16 at 20:21:38.883+00:00


// Top non-terminals: comp_op with_stmt


%%

%public
comp_op:
	  LESS
	| GREATER
	| EQEQUAL
	| GREATEREQUAL
	| LESSEQUAL
	| NOTEQUAL
	| IN
	| NOT IN
	| IS
	| IS NOT
	{} ;

%public
with_stmt:
	  WITH test _optional(with_var {}) COLON suite
	{} ;

%public
with_var: // Used in: with_stmt
	  AS expr
	{} ;


%%


