// Grammar for versions:    3.0    3.1    3.2                     
// Generated by CompareGrammar on 2018-01-16 at 20:21:38.881+00:00


%%

%public
yield_expr:
	  YIELD _optional(testlist {})
	{} ;


%%


