// Grammar for versions:           3.1    3.2  3.3.0  3.5.0  3.6.0
// Generated by CompareGrammar on 2018-01-16 at 20:21:38.886+00:00


// Top non-terminals: comp_op with_stmt


%%

%public
with_item: // Used in: with_stmt
	  test _optional(AS expr {})
	{} ;

%public
with_stmt:
	  WITH with_item _star(COMMA with_item {}) COLON suite
	{} ;

%public
comp_op:
	  LESS
	| GREATER
	| EQEQUAL
	| GREATEREQUAL
	| LESSEQUAL
	| GRLT
	| NOTEQUAL
	| IN
	| NOT IN
	| IS
	| IS NOT
	{} ;


%%


