// Grammar for versions:                       3.3.0  3.5.0  3.6.0
// Generated by CompareGrammar on 2018-01-16 at 20:21:38.890+00:00


%%

%public
yield_expr:
	  YIELD _optional(yield_arg {})
	{} ;

%public
yield_arg: // Used in: yield_expr
	  FROM test
	| testlist
	{} ;


%%


