// Grammar for versions:    2.0    2.2    2.4  2.4.3    2.5              
// Generated by CompareGrammar on 2018-01-16 at 20:28:52.956+00:00


// Top non-terminals: arglist except_clause


%%

%public
arglist:
	  _star(argument COMMA {}) _choice(argument _optional(COMMA {}) | STAR test _optional(COMMA DOUBLESTAR test {}) | DOUBLESTAR test {})
	{} ;

%public
except_clause:
	  EXCEPT _optional(test _optional(COMMA test {}) {})
	{} ;


%%


