// Grammar for versions:                  2.4                            
// Generated by CompareGrammar on 2018-01-16 at 20:28:52.999+00:00


%%

%public
argument:
	  _optional(test EQUAL {}) test _optional(gen_for {})
	{} ;


%%


