// Grammar for versions:                  2.4  2.4.3    2.5              
// Generated by CompareGrammar on 2018-01-16 at 20:28:52.997+00:00


%%

%public
funcdef:
	  _optional(decorators {}) DEF NAME parameters COLON suite
	{} ;


%%


