// Grammar for versions:                       2.4.3    2.5    2.6       
// Generated by CompareGrammar on 2018-01-16 at 20:28:52.950+00:00


%%

%public
argument:
	  test _optional(gen_for {})
	| test EQUAL test
	{} ;


%%


