// Grammar for versions:                  2.4  2.4.3    2.5    2.6       
// Generated by CompareGrammar on 2018-01-16 at 20:28:53.021+00:00


// Top non-terminals: gen_iter testlist_gexp


%%

%public
gen_iter:
	  gen_for
	| gen_if
	{} ;

%public
testlist_gexp:
	  test _choice(gen_for | _star(COMMA test {}) _optional(COMMA {}) {})
	{} ;


%%


